# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - go

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7D07A0DAB2F34D759B6F840BC96E017D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B8F7D070FC464A46BBA19D5AB9CE42A1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3591AFC073FB4573BF3B1E4F2C2200CA }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'go'
          slot-name: 'Production'
          package: .
          
      - name: Install dependencies
        run: npm install
        working-directory: ./ # or ./Web-App-Projects if your code is inside a subfolder
        
      - name: Build
        run: npm run build --if-present
        working-directory: ./ # or ./Web-App-Projects
        
      - name: Test
        run: npm run test --if-present
        working-directory: ./ # or ./Web-App-Projects
